### ISSUE TITLE
Why does it use DateTime instead of NaiveDate

### ISSUE THREAD

**Issue by shrektan** [raymon1/financial#6]
Hi, 

I'm curious that why this package uses DateTime with the TimeZone to be as the Cashflow Constructor. 

Using NaiveDate (the Date class without HMS and TimeZone) feels much more natural to me, as Excel functions usually don't use HMS (the time part) and the TimeZone info at all.

Thanks.

**Comment by raymon1** [comment]
Hi,

Good questions, it seemed more natural to me as it's more generic and you can always convert NaiveDate to DateTime, however doig the opposite, will drop some info. 

That being said, you still have a point, and it might be useful to introduce another interface. would you like to create a PR for that?

**Comment by shrektan** [comment]
Happy to. Probably I should put the functions that accept NaiveDate as the input in a `pub mod` like `dateapi`? So use it like `financial::dateapi::xirr(...)`.

**Comment by raymon1** [comment]
yes, maybe financial::naiveDate::
